workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    environment:
      vars:
        BASE_URL: "https://portfolioproject-production-2b3b.up.railway.app"
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          flutter pub get
      - name: Build Android APK
        script: |
          cd frontend
          flutter build apk --release
    artifacts:
      - frontend/build/app/outputs/flutter-apk/app-release.apk